# Atari-specific 100K benchmark parameters
suite_name: "atari"
task_name: "Breakout-v5"
image_res: [64,64]
image_keys: ["image"]
vector_keys: []
extra_keys: []
seed: ${seed}
sticky: False
model_steps_per_env_step: 256
