# DeepMindControlSuite-specific parameters
suite_name: "dmc"
task_name: "walker-walk-v0"
image_res: [64,64]
image_keys: ["image"]
vector_keys: []
extra_keys: []
seed: ${seed}
model_steps_per_env_step: 256
