defaults:
  - model: 12m
  - env: minigrid
  - _self_

# Experiment Settings
seed: 0
device: "cuda"
total_steps: 1e6
batch_size: 16
batch_length: 64
compile: True
eval_every: 10000
n_eval_episodes: 10
save_every: 10000
log_every: 500
prefill_steps: 2500
# Whether to save a new set of weights every time, or overwrite
checkpoint: False
weights_dir: "./storage/weights/"
log_dir: "./storage/logs/"
load_existing: False
load_existing_path: "./storage/weights/latest.pt"
wandb: True
wandb_project: "dreamerv3-pytorch"

replay:
  capacity: 1e6
  disk_path: "./storage/replay_buffer/"
  load_existing: False
  save_every: ${save_every}

